"""
Pipeline orchestrator module.
This module merges independent feature CSV outputs into one extracted feature file.
"""

import subprocess
from pathlib import Path

import pandas as pd
import psutil
import torch


class FeatureMerger:
    """Merge YOLO and SegFormer feature CSV files."""

    def __init__(
        self,
        yolo_csv_path: str = "./yolo_features.csv",
        segformer_csv_path: str = "./segformer_features.csv",
        output_csv_path: str = "./extracted_features.csv",
    ) -> None:
        """Initialize merger paths.

        Args:
            yolo_csv_path: CSV generated by YOLO extractor.
            segformer_csv_path: CSV generated by SegFormer extractor.
            output_csv_path: Output merged CSV path.
        """
        self.yolo_csv_path = Path(yolo_csv_path)
        self.segformer_csv_path = Path(segformer_csv_path)
        self.output_csv_path = Path(output_csv_path)

    def _validate_inputs(self) -> None:
        """Validate that required source CSV files exist."""
        missing_files = []
        if not self.yolo_csv_path.exists():
            missing_files.append(str(self.yolo_csv_path))
        if not self.segformer_csv_path.exists():
            missing_files.append(str(self.segformer_csv_path))

        if missing_files:
            raise FileNotFoundError(
                "Required CSV files are missing: " + ", ".join(missing_files)
            )

    def merge_features(self) -> pd.DataFrame:
        """Load and merge YOLO and SegFormer features.

        Returns:
            Merged DataFrame from inner join on image_filename.
        """
        self._validate_inputs()

        yolo_df = pd.read_csv(self.yolo_csv_path)
        segformer_df = pd.read_csv(self.segformer_csv_path)

        if "image_filename" not in yolo_df.columns:
            raise ValueError("YOLO CSV must contain 'image_filename' column.")
        if "image_filename" not in segformer_df.columns:
            raise ValueError("SegFormer CSV must contain 'image_filename' column.")

        merged_df = yolo_df.merge(segformer_df, on="image_filename", how="inner")
        if merged_df.empty:
            raise ValueError(
                "Merged DataFrame is empty. Check filename consistency between CSV files."
            )

        return merged_df

    def run(self) -> None:
        """Execute merge and save extracted feature CSV."""
        merged_df = self.merge_features()
        merged_df.to_csv(self.output_csv_path, index=False)

        print("[Main] Feature merge completed successfully.")
        print(f"[Main] Output file: {self.output_csv_path}")
        print(f"[Main] Total merged rows: {len(merged_df)}")
        print(f"[Main] Output columns: {list(merged_df.columns)}")


def log_memory_profile() -> None:
    """Log process RAM and CUDA VRAM usage in MB."""
    process = psutil.Process()
    peak_ram_mb = process.memory_info().rss / (1024 * 1024)

    peak_vram_mb = 0.0
    if torch.cuda.is_available():
        peak_vram_mb = torch.cuda.max_memory_allocated() / (1024 * 1024)

    print(
        f"[Memory Profiler] Peak RAM: {peak_ram_mb:.0f} MB | "
        f"Peak VRAM: {peak_vram_mb:.0f} MB"
    )


def main() -> None:
    """Entrypoint for full subprocess-based pipeline orchestration."""
    if torch.cuda.is_available():
        torch.cuda.reset_peak_memory_stats()

    try:
        print("[Stage 1] YOLO Extraction")
        subprocess.run(["python", "extractors/extractor_yolo.py"], check=True)

        print("[Stage 2] SegFormer Extraction")
        subprocess.run(["python", "extractors/extractor_segformer.py"], check=True)

        print("[Stage 3] Merging CSVs")
        merger = FeatureMerger(
            yolo_csv_path="./yolo_features.csv",
            segformer_csv_path="./segformer_features.csv",
            output_csv_path="./extracted_features.csv",
        )
        merger.run()

        print("[Stage 4] AutoGluon Training")
        subprocess.run(["python", "model_predictor.py"], check=True)

        print("[Main] Pipeline completed successfully.")
    except subprocess.CalledProcessError as exc:
        print(f"[Main][ERROR] Subprocess failed with exit code {exc.returncode}: {exc}")
    except Exception as exc:
        print(f"[Main][ERROR] {exc}")
    finally:
        log_memory_profile()


if __name__ == "__main__":
    main()
